# Generated by Django 3.1.3 on 2020-11-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('tier', models.IntegerField()),
                ('description', models.CharField(max_length=256)),
                ('rarity', models.IntegerField()),
                ('elemental_type', models.CharField(choices=[('anemo', 'Anemo'), ('cryo', 'Cryo'), ('electro', 'Electro'), ('dendro', 'Dendro'), ('geo', 'Geo'), ('hydro', 'Hydro'), ('pyro', 'Pyro')], max_length=16)),
                ('weapon_type', models.CharField(choices=[('bow', 'BOW'), ('catalyst', 'Catalyst'), ('claymore', 'Claymore'), ('polearm', 'Polearm'), ('sword', 'Sword')], max_length=16)),
            ],
        ),
    ]
