# Generated by Django 3.1.3 on 2020-12-19 22:45

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_auto_20201219_0316'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementalSkill',
            fields=[
                ('skilltalent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='characters.skilltalent')),
                ('text', markdownx.models.MarkdownxField()),
                ('values', models.JSONField(blank=True, default=dict)),
            ],
            bases=('characters.skilltalent',),
        ),
        migrations.AlterField(
            model_name='normalattack',
            name='values',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
