# Generated by Django 3.1.3 on 2020-12-19 23:11

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_auto_20201219_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementalBurst',
            fields=[
                ('skilltalent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='characters.skilltalent')),
                ('text', markdownx.models.MarkdownxField()),
                ('values', models.JSONField(blank=True, default=dict)),
            ],
            bases=('characters.skilltalent',),
        ),
    ]
