# Generated by Django 3.1.3 on 2020-12-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_elementalburst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltalent',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
