# Generated by Django 3.1.3 on 2021-01-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_auto_20201219_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltalent',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
