version: "3.7"

services:
  web:
    image: "${WEB_IMAGE}"
    command: gunicorn genshindb.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    ports:
      - 8000:8000
    env_file: .env
  nginx:
    image: "${NGINX_IMAGE}"
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
      - /etc/ssl/certs:/etc/ssl/certs
      - /etc/ssl/private:/etc/ssl/private
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
